version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - pip install requests -t .
      - >-
        aws cloudformation package --template template.yml --s3-bucket
        rajsaha-codedeploy --output-template template-export.yml
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'
